name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
          
      - name: Install virtualenv, requeriments and Pytest
        run: |
          pip install virtualenv
          virtualenv env
          source env/bin/activate
          
          pip install -r requirements.txt
          
          cd punto_3/clientes 
          pytest
          python kinesis.py
          
      #- name: Update code
      #  run: |
      #    source env/bin/activate
      #    aws s3 cp punto2/parcial_3_noticias.ipynb s3://aws-emr-resources-070749073205-us-east-1/notebooks/e-5SG6CJ0IP3D4A34H9K2ZOYW7S/
